Excercise
maybe-hello-world/PY111-template pull request #20
Opened 2019-04-19 18:11 UTC by IlyaChristianov

task 0

2019-04-19 18:11 UTC, pep8speaks commented
Hello @IlyaChristianov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`Tasks/a0_my_stack.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/a0_my_stack.py):

> [Line 45:15](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/a0_my_stack.py#L45): [E226](https://duckduckgo.com/?q=pep8%20E226) missing whitespace around arithmetic operator

* In the file [`Tasks/a3_check_brackets.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/a3_check_brackets.py):

> [Line 8:14](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/a3_check_brackets.py#L8): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`Tasks/c0_fib.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c0_fib.py):

> [Line 18:13](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c0_fib.py#L18): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`Tasks/c1_fact.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c1_fact.py):

> [Line 9:1](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c1_fact.py#L9): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 16:13](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c1_fact.py#L16): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`Tasks/c2_recursive_binary_search.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c2_recursive_binary_search.py):

> [Line 10:13](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/c2_recursive_binary_search.py#L10): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`Tasks/d0_stairway.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/d0_stairway.py):

> [Line 8:13](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/d0_stairway.py#L8): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`Tasks/d1_horse.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/d1_horse.py):

> [Line 4:1](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/d1_horse.py#L4): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 10:101](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tasks/d1_horse.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)

* In the file [`Tests/a3_test_check_brackets.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/a3_test_check_brackets.py):

> [Line 17:17](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/a3_test_check_brackets.py#L17): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`Tests/c0_test_fib.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py):

> [Line 8:7](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L8): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 8:8](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L8): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 12:8](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L12): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 12:11](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L12): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 12:101](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L12): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 100 characters)
> [Line 17:7](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L17): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 17:8](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L17): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 21:8](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L21): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 21:11](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L21): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 21:101](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c0_test_fib.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 100 characters)

* In the file [`Tests/c1_test_fact.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c1_test_fact.py):

> [Line 15:101](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c1_test_fact.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 100 characters)

* In the file [`Tests/c2_test_recursive_binary_search.py`](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_binary_search.py):

> [Line 16:7](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_binary_search.py#L16): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 16:9](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_binary_search.py#L16): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 18:7](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_binary_search.py#L18): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 18:9](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_binary_search.py#L18): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 22:7](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_binary_search.py#L22): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 22:8](https://github.com/maybe-hello-world/PY111-april/blob/87c4f7148b955f119ae516c402a1f444133e3cc6/Tests/c2_test_recursive_bin [...]

2019-04-19 20:40 UTC, maybe-hello-world requested changes
См. комментарии.

2019-04-19 20:40 UTC, maybe-hello-world commented on Tasks/a0_my_stack.py
> +    for i in a:
Что это?
Блокирующий комментарий.

2019-04-19 20:40 UTC, maybe-hello-world commented on Tasks/a0_my_stack.py
> +    for i in a:
Данный цикл не выполняет peek элемента в стеке. Необходимо исправить.

2019-04-20 06:18 UTC, IlyaChristianov commented
"""
My little Stack
"""
a = []
def push(elem) -> None:
"""
Operation that add element to stack
:param elem: element to be pushed
:return: Nothing
"""
a.append(elem)
return None
def pop():
"""
Pop element from the top of the stack
:return: popped element
"""
global a
if len(a) == 0:
return None
else:
result = a[-1]
del a[-1]
return result
def peek(ind: int = 0):
"""
Allow you to see at the element in the stack without popping it
:param ind: index of element (count from the top)
:return: peeked element
"""
global a
for i in a:
if i < 0:
return None
else:
return a[-1-ind]
def clear() -> None:
"""
Clear my stack
:return: None
"""
global a
a = []
return None

пт, 19 апр. 2019 г. в 23:40, Roman Beltyukov <notifications@github.com>:

> *@maybe-hello-world* requested changes on this pull request.
>
> См. комментарии.
> ------------------------------
>
> In Tasks/a0_my_stack.py
> <https://github.com/maybe-hello-world/PY111-april/pull/20#discussion_r277086583>
> :
>
> >
>
> -	:param ind: index of element (count from the top)
>
> -	:return: peeked element
>
> -	"""
>
> -	return None
>
> +    :param ind: index of element (count from the top)
>
> +    :return: peeked element
>
> +    """
>
> +    global a
>
> +    for i in a:
>
>
> Что это?
> Блокирующий комментарий.
> ------------------------------
>
> In Tasks/a0_my_stack.py
> <https://github.com/maybe-hello-world/PY111-april/pull/20#discussion_r277086715>
> :
>
> >
>
> -	:param ind: index of element (count from the top)
>
> -	:return: peeked element
>
> -	"""
>
> -	return None
>
> +    :param ind: index of element (count from the top)
>
> +    :return: peeked element
>
> +    """
>
> +    global a
>
> +    for i in a:
>
>
> Данный цикл не выполняет peek элемента в стеке. Необходимо исправить.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/maybe-hello-world/PY111-april/pull/20#pullrequestreview-228820148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AL2ZXGAJQSAQSLZSYOGZHXTPRIU3PANCNFSM4HHGLPDQ>
> .
>

2019-04-20 06:23 UTC, IlyaChristianov commented
Это то что у меня на Git'e и я не понимаю как это все работает, почему вы
видите не тоже самое и как сделать клон локально себе, все операции
выполняла Любовь и на моем примере показала всем как должно быть итог по
приходу домой я клонировал себе локально только ваши задания без моих
комитов. Почему я не знаю...не уверен что я разберусь сам почему так.....но
я буду пробовать, а пока все по старинке без Git'a

сб, 20 апр. 2019 г. в 09:18, Илья Христианов <ilyachristianov@gmail.com>:

> """
> My little Stack
> """
> a = []
> def push(elem) -> None:
> """
> Operation that add element to stack
> :param elem: element to be pushed
> :return: Nothing
> """
> a.append(elem)
> return None
> def pop():
> """
> Pop element from the top of the stack
> :return: popped element
> """
> global a
> if len(a) == 0:
> return None
> else:
> result = a[-1]
> del a[-1]
> return result
> def peek(ind: int = 0):
> """
> Allow you to see at the element in the stack without popping it
> :param ind: index of element (count from the top)
> :return: peeked element
> """
> global a
> for i in a:
> if i < 0:
> return None
> else:
> return a[-1-ind]
> def clear() -> None:
> """
> Clear my stack
> :return: None
> """
> global a
> a = []
> return None
>
> пт, 19 апр. 2019 г. в 23:40, Roman Beltyukov <notifications@github.com>:
>
>> *@maybe-hello-world* requested changes on this pull request.
>>
>> См. комментарии.
>> ------------------------------
>>
>> In Tasks/a0_my_stack.py
>> <https://github.com/maybe-hello-world/PY111-april/pull/20#discussion_r277086583>
>> :
>>
>> >
>>
>> -	:param ind: index of element (count from the top)
>>
>> -	:return: peeked element
>>
>> -	"""
>>
>> -	return None
>>
>> +    :param ind: index of element (count from the top)
>>
>> +    :return: peeked element
>>
>> +    """
>>
>> +    global a
>>
>> +    for i in a:
>>
>>
>> Что это?
>> Блокирующий комментарий.
>> ------------------------------
>>
>> In Tasks/a0_my_stack.py
>> <https://github.com/maybe-hello-world/PY111-april/pull/20#discussion_r277086715>
>> :
>>
>> >
>>
>> -	:param ind: index of element (count from the top)
>>
>> -	:return: peeked element
>>
>> -	"""
>>
>> -	return None
>>
>> +    :param ind: index of element (count from the top)
>>
>> +    :return: peeked element
>>
>> +    """
>>
>> +    global a
>>
>> +    for i in a:
>>
>>
>> Данный цикл не выполняет peek элемента в стеке. Необходимо исправить.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/maybe-hello-world/PY111-april/pull/20#pullrequestreview-228820148>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AL2ZXGAJQSAQSLZSYOGZHXTPRIU3PANCNFSM4HHGLPDQ>
>> .
>>
>

2019-04-20 17:35 UTC, maybe-hello-world commented
Окей. Как разберетесь - присылайте. :)
Задавайте мне вопросы на ближайшей практике. До нее: забэкапьте свои изменения и попробуйте еще раз выполнить инструкции из README из корня репозитория. 
Чтобы добавить коммиты в этот пулл request нужно просто добавлять коммиты в ветку Hristianov и пушить их в свой репозиторий.

2019-05-13 09:54 UTC, maybe-hello-world commented
Ап

2019-10-06 16:44 UTC, closed without merging