Практика, задания а0_а1_а2_а3
maybe-hello-world/PY111-template pull request #22
Opened 2019-04-22 17:21 UTC by BruderOrun

a2_clear , что то никак не проходит тест, возможно напортачил с каким то другим методом.

2019-04-23 07:48 UTC, pep8speaks commented
Hello @BruderOrun! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`Tasks/a0_my_stack.py`](https://github.com/maybe-hello-world/PY111-april/blob/a9dc8d965161f19387c5aa9006f7f57ae9d846b0/Tasks/a0_my_stack.py):

> [Line 51:24](https://github.com/maybe-hello-world/PY111-april/blob/a9dc8d965161f19387c5aa9006f7f57ae9d846b0/Tasks/a0_my_stack.py#L51): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2019-04-23 08:25 UTC, maybe-hello-world requested changes
См. блокирующие комментарии + комментарии от бота

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a0_my_stack.py
> +    except(IndexError):
```suggestion
    except IndexError:
```
Более принятый на настоящий момент синтаксис

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a0_my_stack.py
> +    return stak.clear()
Функция clear() ничего не возвращает -> будет возвращен None. Лучше явно писать return None или не писать return вообще, чем в такой записи, т.к. отдельно приходится проверять, что возвращает та функция.

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    return stak.append(elem)
аналогично см. выше

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    if stak is not None:
А если stak не None, но там 0 элементов?
Блокирующий комментарий.

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    if stak is not None:
И здесь неверно, сам stak не None (потому что пустой список != None), но элементов таких там может не быть (и if stak[ind] эту проверку не делает).
Скорее всего здесь и валится.
Блокирующий.

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +test_dict = [[], [], [], [], []]
0 to 5 == 6 очередей

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +        if test_dict[i]:
Не проверяет эта конструкция на наличие объекта

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +    return test_dict[priority][ind] if test_dict[priority][ind] else None
см. выше, блокирующий

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +        i = None
ой-ой-ой, а что произойдет, если я скажу enqueue в очередь после clear? Вы же очереди удалили, они теперь у вас None, и append к ним применить нельзя...
Блокирующий.

2019-04-23 08:25 UTC, maybe-hello-world commented on Tasks/a3_check_brackets.py
> +    return False if s != d else True
Отличное решение, кое чего не хватает.
')(' вот на такую строку он ругаться не будет, а должен.
Да и вообще, зачем вам две переменные...

2019-04-23 13:05 UTC, maybe-hello-world requested changes
См. комментарии

2019-04-23 13:05 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
>          return stak[ind] if stak[ind] else None
Проблема то все та же осталась...
Блокирующий

2019-04-23 13:05 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +        return test_dict[priority][ind]
Аналогично.

2019-04-23 13:13 UTC, BruderOrun commented on Tasks/a1_my_queue.py
>          return stak[ind] if stak[ind] else None
Видимо просто недопонимаю, что не так ((
Старые комменты затерлись не пойму где они,
не перечитать.

2019-04-23 13:14 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
>          return stak[ind] if stak[ind] else None
Представьте, что у вас стек == [1, 2]. А я прошу peek(19).

2019-04-27 09:20 UTC, maybe-hello-world requested changes
См. комментарии

2019-04-27 09:20 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +            return stak[ind] if stak[ind] else None
В чем смысл этой проверки? Если я добавлю в список элемент 0, он мне вместо него вернет None, потому что if stak[ind] мне вернет False.
Блокирующий.

Не стоит просто брать и костылями чинить неработающие вещи. Надо подумать, почему они не работают и делать правильно. :)

2019-04-27 09:20 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +test_dict = [[1], [2], [3], [], [], []]
ОО
Я понимаю, что для тестирования, но в итоговом варианте то оно здесь зачем?)
Блокирующий.

2019-04-30 14:12 UTC, maybe-hello-world requested changes
См. комментарии

2019-04-30 14:12 UTC, maybe-hello-world commented on Tasks/b0_linear_search.py
> +    a = 0
А если в массиве все числа строго больше 0?
Блокирующий

2019-05-13 09:55 UTC, maybe-hello-world commented
Ап

2019-05-14 17:46 UTC, maybe-hello-world commented on Tasks/b0_linear_search.py
> +    a = 0
Доделайте вы уже этот дурацкий баг :)

2019-05-18 07:42 UTC, maybe-hello-world approved these changes

2019-05-18 07:43 UTC, merged