Metelev
maybe-hello-world/PY111-template pull request #23
Opened 2019-04-24 16:02 UTC by fastscript

exersize a1_my_queue.py

2019-04-24 16:02 UTC, pep8speaks commented
Hello @fastscript! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`Tasks/b0_linear_search.py`](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tasks/b0_linear_search.py):

> [Line 14:11](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tasks/b0_linear_search.py#L14): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file





* In the file [`Tasks/e2_dijkstra.py`](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tasks/e2_dijkstra.py):

> [Line 10:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tasks/e2_dijkstra.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (105 > 100 characters)













* In the file [`Tests/e0_test_breadth_first_search.py`](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e0_test_breadth_first_search.py):

> [Line 29:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e0_test_breadth_first_search.py#L29): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 100 characters)

* In the file [`Tests/e1_test_depth_first_search.py`](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e1_test_depth_first_search.py):

> [Line 22:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e1_test_depth_first_search.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 100 characters)

* In the file [`Tests/e2_test_dijkstra.py`](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e2_test_dijkstra.py):

> [Line 37:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e2_test_dijkstra.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)
> [Line 46:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e2_test_dijkstra.py#L46): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)
> [Line 55:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/e2_test_dijkstra.py#L55): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 100 characters)









* In the file [`Tests/h0_test_KMP.py`](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/h0_test_KMP.py):

> [Line 19:5](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/h0_test_KMP.py#L19): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 19:8](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/h0_test_KMP.py#L19): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 21:101](https://github.com/maybe-hello-world/PY111-april/blob/f942bd6fde0645c2132fb47346ec7322a047f660/Tests/h0_test_KMP.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (112 > 100 characters)

2019-04-24 16:59 UTC, maybe-hello-world requested changes
См. комментарии

2019-04-24 16:59 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    q.append(elem)
q.insert

2019-04-24 16:59 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    return q[len(q) - ind - 1]
А если такого элемента нет?

2019-04-24 16:59 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    return q[len(q) - ind - 1]
Блокирующий

2019-04-24 16:59 UTC, maybe-hello-world commented on Tasks/a1_my_queue.py
> +    q.append(elem)
Блокирующий

2019-04-27 09:26 UTC, maybe-hello-world requested changes
См. комментарии

2019-04-27 09:26 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +	del q[priority]
А нужно ли это удаление и лишние операции? Проверьте, что будет, если просто insert сделать, а эту строчку убрать (с дебаггером).

2019-04-27 09:26 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +	del q[priority]
Блокирующий

2019-04-27 09:26 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +	if q[5] != []:
Очень страшный алгоритм :)
Оберните это хотя бы в цикл от 5 до 0, все равно одинаковые инструкции же выполняете.
А еще лучше - внимательно посмотрите и разберитесь, нужно ли удалять вообще q[5]

2019-04-27 09:26 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +	if q[5] != []:
Блокирующий

2019-04-27 09:26 UTC, maybe-hello-world commented on Tasks/b1_binary_search.py
> +	return (m + n) // 2
Да сохраните вы int((m + n) // 2) в переменную и используйте везде ее, а не вычисляйте заново :)

2019-04-27 09:26 UTC, maybe-hello-world commented on Tasks/b1_binary_search.py
> +	return (m + n) // 2
Неблокирующий, но лучше исправить.

2019-04-27 14:29 UTC, maybe-hello-world commented
Последнее задание ок, исправляйте комменты

2019-05-13 08:09 UTC, maybe-hello-world requested changes
Смотри единственный комментарий, остальное принято и неплохо сделано :)

2019-05-13 08:09 UTC, maybe-hello-world commented on Tasks/a2_priority_queue.py
> +    return qq[ind]
Вы вставляете в начало очереди и пик делаете тоже из начала, это точно так должно быть? 
Блокирующий

2019-05-14 22:15 UTC, fastscript commented on Tasks/a2_priority_queue.py
> +    return qq[ind]
Роман, я все проверил, мне кажется, все верно: я добавляю элемент слева очереди (начало), а беру справа... с конца
Ведь так и должно быть?

2019-05-18 07:40 UTC, maybe-hello-world requested changes
Вы реализовали наивный поиск подстроки в строке, не КМП. :)

2019-05-18 07:40 UTC, maybe-hello-world commented on Tasks/g1_merge_sort.py
> +                del cont2[0]
Вообще удаление из начала списка - O(n), поэтому нежелательно так делать. Лучше завести счетчики, которые будут идти от начала каждого из списков до конца...
Неблокирующий.

2019-10-06 16:44 UTC, closed without merging